import neostandard from 'neostandard'
import globals from 'globals'
import html from 'eslint-plugin-html'

export default [
  {
    // Generated by `npm run build` — vendored/bundled code, not authored.
    // Plus scratch/local-history folders that are not part of the app.
    ignores: [
      'docs/app.js',
      'docs/sw.js',
      'docs/chunks',
      '.dev',
      'todo',
      '.history',
      'dist',
      'node_modules'
    ]
  },
  ...neostandard({
    // options
  }), {
    files: ['**/*.js', '**/*.html'],
    plugins: { html },
    languageOptions: {
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.serviceworker,
        IS_DEVELOPMENT: 'readonly',
        IS_PRODUCTION: 'readonly',
        LAUNCHER_SW_VERSION: 'readonly',
        LAUNCHER_DEPLOY_HASH: 'readonly'
      }
    },
    rules: {
      '@stylistic/comma-dangle': ['error', 'never'], // @stylistic/js/... isn't supported by neostandard yet
      '@stylistic/lines-between-class-members': 'off',
      '@stylistic/object-property-newline': 'off',
      'import/no-anonymous-default-export': 'off',
      'no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_', varsIgnorePattern: '^_$' }
      ],
      'one-var': 'off'
    }
  }
]
